import './globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";

const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={plus_jakarta_sans.className}>
    <Header />
    <main>{children}</main>
    <Footer />
    </body>
    </html>
  )
}
